//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by winmain.rc
//
#define IDS_OBJTAB1                     1
#define IDS_CTR_BOTTOM1                 1
#define IDS_BOTTOM_VATAL                1
#define IDS_OBJTAB2                     2
#define IDS_CTR_BOTTOM2                 2
#define IDS_BOTTOM_MANA                 2
#define IDS_STRING3                     3
#define IDS_CTR_BOTTOM3                 3
#define IDS_BOTTOM_STAMINER             3
#define IDS_BOTTOM_STAMINA              3
#define IDS_CTR_BOTTOM4                 4
#define IDS_BOTTOM_EPOWER               4
#define IDS_CTR_BOTTOM5                 5
#define IDS_BOTTOM_SOCAIL               5
#define IDS_CTR_BOTTOM6                 6
#define IDS_BOTTOM_MOTION_MODE          6
#define IDS_CTR_BOTTOM7                 7
#define IDS_BOTTOM_CHAT_MODE            7
#define IDS_LOGIN_PG1                   8
#define IDS_LOGIN_INPUT_ID              8
#define IDS_LOGIN_PG2                   9
#define IDS_LOGIN_INPUT_PASS            9
#define IDS_LOGIN_PG3                   10
#define IDS_LOGIN_ID_LIMIT              10
#define IDS_LOGIN_PG4                   11
#define IDS_LOGIN_PASSWORD_LIMIT        11
#define IDS_LOGIN_PG5                   12
#define IDS_LOGIN_CONFIRM               12
#define IDS_LOGIN_PG6                   13
#define IDS_LOGIN_CONNECT_FAIL          13
#define IDS_MAKEACCOUNT_PG1             14
#define IDS_MAKEACC_CANNOT_CONNECT      14
#define IDS_MAKEACCOUNT_PG2             15
#define IDS_MAKEACC_CREATED_ACC         15
#define IDS_MAKEACCOUNT_PG3             16
#define IDS_MAKEACC_SEVER_TEST          16
#define IDS_MAKEACCOUNT_PG4             17
#define IDS_MAKEACC_EXIST_ID            17
#define IDS_MAKEACCOUNT_PG5             18
#define IDS_MAKEACC_CONFIRM_ITEM        18
#define IDS_MAKEACCOUNT_PG6             19
#define IDS_MAKEACC_INPUT_NAME          19
#define IDS_MAKEACCOUNT_PG7             20
#define IDS_MAKEACC_NARROW_NAME         20
#define IDS_MAKEACCOUNT_PG8             21
#define IDS_MAKEACC_NARROW_ID           21
#define IDS_MAKEACCOUNT_PG9             22
#define IDS_MAKEACC_ID_LIMIT            22
#define IDS_MAKEACCOUNT_PG10            23
#define IDS_MAKEACC_UNABLE_STRING_ID    23
#define IDS_MAKEACCOUNT_PG11            24
#define IDS_MAKEACC_UNABLE_STRING_NAME  24
#define IDS_MAKEACCOUNT_PG12            25
#define IDS_MAKEACC_INPUT_PASS          25
#define IDS_MAKEACCOUNT_PG13            26
#define IDS_MAKEACC_PASS_LIMIT          26
#define IDS_MAKEACCOUNT_PG14            27
#define IDS_MAKEACC_UNABLE_HANGEUL      27
#define IDS_MAKEACCOUNT_PG15            28
#define IDS_MAKEACC_NARROW_PASS         28
#define IDS_MAKEACCOUNT_PG16            29
#define IDS_MAKEACC_INPUT_EMAIL         29
#define IDS_MAKEACCOUNT_PG17            30
#define IDS_MAKEACC_NARROW_EMAIL        30
#define IDS_MAKEACCOUNT_PG18            31
#define IDS_MAKEACC_INPUT_QUESTION      31
#define IDS_MAKEACCOUNT_PG19            32
#define IDS_MAKEACC_INPUT_ANSWER        32
#define IDS_MAKEACCOUNT_PG20            33
#define IDS_MAKEACC_INPUT_JUMIN         33
#define IDS_MAKEACCOUNT_PG21            34
#define IDS_MAKEACC_NARROW_JUMIN        34
#define IDS_MAKEACCOUNT_PG22            35
#define IDS_MAKEACC_FAULT_JUMIN         35
#define IDS_MAKEACCOUNT_PG23            36
#define IDS_MAKEACC_ENABLE_NUMBER       36
#define IDS_SELCHA_PG1                  37
#define IDS_SELCHA_CHA_DELETE           37
#define IDS_SELCHA_PG2                  38
#define IDS_SELCHA_FAULT_PASS           38
#define IDS_CRECHA_PG1                  39
#define IDS_CRECHA_BULKAN               39
#define IDS_CRECHA_PG2                  40
#define IDS_CRECHA_KAI                  40
#define IDS_CRECHA_PG3                  41
#define IDS_CRECHA_ADI                  41
#define IDS_CRECHA_PG4                  42
#define IDS_CRECHA_HUNMAN               42
#define IDS_CRECHA_PG5                  43
#define IDS_CRECHA_MALE                 43
#define IDS_CRECHA_PG6                  44
#define IDS_CRECHA_FEMALE               44
#define IDS_CRECHA_PG7                  45
#define IDS_CRECHA_HAIR_01              45
#define IDS_CRECHA_PG8                  46
#define IDS_CRECHA_HAIR_02              46
#define IDS_CRECHA_PG9                  47
#define IDS_CRECHA_HAIR_03              47
#define IDS_CRECHA_PG10                 48
#define IDS_CRECHA_HAIR_04              48
#define IDS_CRECHA_PG11                 49
#define IDS_CRECHA_HAIR_05              49
#define IDS_CRECHA_PG12                 50
#define IDS_CRECHA_HAIR_06              50
#define IDS_CRECHA_PG13                 51
#define IDS_CRECHA_HAIR_07              51
#define IDS_CRECHA_PG14                 52
#define IDS_CRECHA_HAIR_08              52
#define IDS_CRECHA_PG15                 53
#define IDS_CRECHA_HAIR_09              53
#define IDS_CRECHA_PG16                 54
#define IDS_CRECHA_HAIR_10              54
#define IDS_CRECHA_PG17                 55
#define IDS_CRECHA_HAIR_11              55
#define IDS_CRECHA_PG18                 56
#define IDS_CRECHA_HAIR_12              56
#define IDS_CRECHA_PG19                 57
#define IDS_CRECHA_HAIR_13              57
#define IDS_CRECHA_PG20                 58
#define IDS_CRECHA_HAIR_14              58
#define IDS_CRECHA_PG21                 59
#define IDS_CRECHA_HAIR_15              59
#define IDS_CRECHA_PG22                 60
#define IDS_CRECHA_HAIR_16              60
#define IDS_CRECHA_PG23                 61
#define IDS_CRECHA_HAIR_17              61
#define IDS_CRECHA_PG24                 62
#define IDS_CRECHA_HAIR_18              62
#define IDS_CRECHA_PG25                 63
#define IDS_CRECHA_HAIR_19              63
#define IDS_CRECHA_PG26                 64
#define IDS_CRECHA_HAIR_20              64
#define IDS_CRECHA_PG27                 65
#define IDS_CRECHA_HAIR_21              65
#define IDS_CRECHA_PG28                 66
#define IDS_CRECHA_INPUT_NAME           66
#define IDS_CRECHA_PG29                 67
#define IDS_CRECHA_NAME_LIMIT           67
#define IDS_CRECHA_PG30                 68
#define IDS_CRECHA_UNABLE_BLANK         68
#define IDS_CRECHA_PG31                 69
#define IDS_CRECHA_UNABLE_STRING_01     69
#define IDS_CRECHA_PG32                 70
#define IDS_CRECHA_UNABLE_STRING_02     70
#define IDS_CRECHA_PG33                 71
#define IDS_CRECHA_USEING_NAEM          71
#define IDS_CRECHA_ALLEADY_EXIST        71
#define IDS_CRECHA_PG34                 72
#define IDS_CRECHA_MANAGEMENT           72
#define IDS_CRECHA_PG35                 73
#define IDS_CRECHA_LAGHAIM_HAN          73
#define IDS_CRECHA_PG36                 74
#define IDS_CRECHA_LAGHAIM_ENG          74
#define IDS_CRECHA_PG37                 75
#define IDS_CRECHA_WHISPER              75
#define IDS_CRECHA_PG38                 76
#define IDS_CRECHA_GUILD                76
#define IDS_CRECHA_PG39                 77
#define IDS_CRECHA_PARTY                77
#define IDS_CRECHA_PG40                 78
#define IDS_CRECHA_MUDORI               78
#define IDS_CRECHA_PG41                 79
#define IDS_CRECHA_SHANGSHANG           79
#define IDS_CRECHA_PG42                 80
#define IDS_CRECHA_GURIWORA             80
#define IDS_SETVALUE_PG1                81
#define IDS_SETVALUE                    81
#define IDS_SELVILLAGE_PG1              82
#define IDS_SELVILLAGE_BASE_BULKAN      82
#define IDS_SELVILLAGE_PG2              83
#define IDS_SELVILLAGE_BASE_KAI         83
#define IDS_SELVILLAGE_PG3              84
#define IDS_SELVILLAGE_BASE_ADI         84
#define IDS_SELVILLAGE_PG4              85
#define IDS_SELVILLAGE_BASE_HUMAN       85
#define IDS_SELVILLAGE_PG5              86
#define IDS_SELVILLAGE_SEL_BASE         86
#define IDS_CTR_EXCHANGE1               87
#define IDS_EXCHANGE_INPUT_MONEY        87
#define IDS_CTR_EXCHANGE2               88
#define IDS_EXCHANGE_UNABLE_BLANK       88
#define IDS_CTR_EXCHANGE3               89
#define IDS_EXCHANGE_UNABLE_STRING      89
#define IDS_CTR_EXCHANGE4               90
#define IDS_EXCHANGE_FAULT_STRING       90
#define IDS_EXCHANGE_FAULT_STR          90
#define IDS_CTR_EXCHANGE5               91
#define IDS_EXCHANGE_SCARCE_MONEY       91
#define IDS_CMD1                        92
#define IDS_CMD                         92
#define IDS_CMD_WHISPER                 92
#define IDS_CTR_INVEN1                  93
#define IDS_INVEN_REQUILE_MORE_LEVEL    93
#define IDS_CTR_INVEN2                  94
#define IDS_INVEN_SCARCE_STR            94
#define IDS_CTR_INVEN3                  95
#define IDS_INVEN_SCARCE_ETC            95
#define IDS_CTR_INVEN4                  96
#define IDS_INVEN_CANNOT_HOLD_SHIELD    96
#define IDS_CTR_INVEN5                  97
#define IDS_INVEN_CANNOT_HOLD_WEPHONE   97
#define IDS_INVEN_CANNOT_HOLD_WEAPON    97
#define IDS_CTR_INVEN6                  98
#define IDS_INVEN_SCARCE_INT            98
#define IDS_CTR_INVEN7                  99
#define IDS_INVEN_CANNOT_HOLD_SHIELD2   99
#define IDS_CTR_INVEN8                  100
#define IDS_INVEN_CANNOT_HOLD_WEPHONE2  100
#define IDS_INVEN_CANNOT_HOLD_WEAPON2   100
#define IDR_MENU                        101
#define IDS_CTR_INVEN9                  101
#define IDS_INVEN_REGUILE_LEVEL         101
#define IDS_CTR_INVEN10                 102
#define IDS_INVEN_DEFANCE               102
#define IDR_MAIN_ACCEL                  103
#define IDS_CTR_INVEN11                 103
#define IDS_INVEN_DEFANCE_MANA_RATE     103
#define IDI_MAIN_ICON                   104
#define IDS_CTR_INVEN12                 104
#define IDS_INVEN_MANA_USE              104
#define IDR_POPUP                       105
#define IDS_CTR_INVEN13                 105
#define IDS_INVEN_TOWHAND_DAMAGE        105
#define IDD_ABOUT                       106
#define IDS_CTR_INVEN14                 106
#define IDS_INVEN_ONEHNAD_DAMAGE        106
#define IDD_CHANGEDEVICE                107
#define IDS_CTR_INVEN15                 107
#define IDS_INVEN_DAMAGE                107
#define IDD_DIALOG_COMM                 108
#define IDS_CTR_INVEN16                 108
#define IDS_INVEN_ELECT_USE             108
#define IDD_DEV_NETLOG                  108
#define IDD_DIALOG_OBJECT               109
#define IDS_CTR_INVEN17                 109
#define IDS_INVEN_VERY_FAST             109
#define IDC_CURSOR1                     110
#define IDS_CTR_INVEN18                 110
#define IDS_INVEN_FAST                  110
#define IDS_CTR_INVEN19                 111
#define IDS_INVEN_SLOW                  111
#define IDS_CTR_INVEN20                 112
#define IDS_INVEN_VERY_SLOW             112
#define IDD_LOGIN_DLG                   113
#define IDS_CTR_INVEN21                 113
#define IDS_INVEN_MID                   113
#define IDS_CTR_INVEN22                 114
#define IDS_INVEN_ATT_SPEED             114
#define IDD_DIALOG1                     115
#define IDS_CTR_INVEN23                 115
#define IDS_INVEN_MANA_SPEED            115
#define IDD_DEV_MAIN                    115
#define IDS_CTR_INVEN24                 116
#define IDS_INVEN_MANA_DAMAGE           116
#define IDD_DEV_STRING                  116
#define IDS_CTR_INVEN25                 117
#define IDS_INVEN_WEIGHT                117
#define IDD_DEV_SKILL                   117
#define IDS_CTR_INVEN26                 118
#define IDS_INVEN_REQUILE_INT           118
#define IDD_DEV_POINTLOG                118
#define IDS_CTR_INVEN27                 119
#define IDS_INVEN_REQUILE_QUICKNESS     119
#define IDS_CTR_INVEN28                 120
#define IDS_CTR_INVEN29                 121
#define IDS_CTR_OPTION1                 122
#define IDS_OPTION_NOT_USE              122
#define IDS_CTR_OPTION2                 123
#define IDS_OPTION_USE                  123
#define IDS_CTR_OPTION3                 124
#define IDS_OPTION_FULL_MODE            124
#define IDS_CTR_OPTION4                 125
#define IDS_OPTION_WINDOWS_MODE         125
#define IDS_CTR_OPTION5                 126
#define IDS_OPTION_NONE_EXPRESSION      126
#define IDS_CTR_OPTION6                 127
#define IDS_OPTION_MY_CHA               127
#define IDS_CTR_OPTION7                 128
#define IDS_OPTION_PLAYER               128
#define IDS_CTR_OPTION8                 129
#define IDS_OPTION_ALL_PLAYER           129
#define IDS_CTR_PARTY1                  130
#define IDS_PARTY                       130
#define IDS_CTR_SCORE1                  131
#define IDS_SCORE_BULKAN                131
#define IDS_CTR_SCORE2                  132
#define IDS_SCORE_KAI                   132
#define IDS_CTR_SCORE3                  133
#define IDS_SCORE_ADI                   133
#define IDS_CTR_SCORE4                  134
#define IDS_SCORE_HUMAN                 134
#define IDS_CTR_SCORE5                  135
#define IDS_SCORE_MALE                  135
#define IDS_CTR_SCORE6                  136
#define IDS_SCORE_FEMALE                136
#define IDS_CTR_SKILL1                  137
#define IDS_SKILL_NEXT_SKILL_LEVEL      137
#define IDS_CTR_SKILL2                  138
#define IDS_SKILL_MANA_DAMAGE_DISTANCE  138
#define IDS_CTR_SKILL3                  139
#define IDS_SKILL_MANA_RECOVERY         139
#define IDS_CTR_SKILL4                  140
#define IDS_SKILL_MANA_DAMAGE_DECREASE  140
#define IDS_CTR_SKILL5                  141
#define IDS_SKILL_MANA_PHISICAL_SHIELD  141
#define IDS_CTR_SKILL6                  142
#define IDS_SKILL_DURATION_TIME         142
#define IDS_CTR_SKILL7                  143
#define IDS_SKILL_DEFANCE               143
#define IDS_CTR_SKILL8                  144
#define IDS_SKILL_RECOVERY_VATAL        144
#define IDS_CTR_SKILL9                  145
#define IDS_SKILL_SUCCESS_RATE          145
#define IDS_CTR_SKILL10                 146
#define IDS_SKILL_SUCCESS_RATE_SEGONG   146
#define IDS_CTR_SKILL11                 147
#define IDS_SKILL_DAMAGE_BOUNS          147
#define IDS_SKILL_DAMAGE_BONUS          147
#define IDS_CTR_SKILL12                 148
#define IDS_SKILL_MAX_SKILL_LEVEL       148
#define IDS_CTR_SOCAIL1                 149
#define IDS_SOCAIL_HAND                 149
#define IDS_CTR_SOCAIL2                 150
#define IDS_SOCAI_GREETING              150
#define IDS_CTR_SOCAIL3                 151
#define IDS_SOCAIL_KISS                 151
#define IDS_CTR_SOCAIL4                 152
#define IDS_SOCAIL_BOW                  152
#define IDS_CTR_SOCAIL5                 153
#define IDS_SOCAIL_GENTLE_GREETING      153
#define IDS_CTR_SOCAIL6                 154
#define IDS_SOCAIL_PARDON               154
#define IDS_CTR_SOCAIL7                 155
#define IDS_SOCAIL_DISCO                155
#define IDS_CTR_SOCAIL8                 156
#define IDS_SOCAIL_JUMP                 156
#define IDS_CTR_SOCAIL9                 157
#define IDS_SOCAIL_CLAP                 157
#define IDS_CTR_SOCAIL10                158
#define IDS_SOCAIL_DELIGHT_CLAP         158
#define IDS_CTR_SOCAIL11                159
#define IDS_SOCAIL_LAUGH                159
#define IDS_CTR_SOCAIL12                160
#define IDS_SOCAIL_AIR_SHOW             160
#define IDS_CTR_SOCAIL13                161
#define IDS_SOCAIL_PARDON2              161
#define IDS_CTR_SOCAIL14                162
#define IDS_SOCAIL_CHEEK_HIT            162
#define IDS_CTR_SOCAIL15                163
#define IDS_SOCAIL_KICK                 163
#define IDS_CTR_SOCAIL16                164
#define IDS_SOCAIL_MELONG               164
#define IDS_CTR_SOCAIL17                165
#define IDS_SOCAIL_TTONG                165
#define IDS_CTR_SOCAIL18                166
#define IDS_SOCAIL_PUT_HEAD             166
#define IDS_CTR_SOCAIL19                167
#define IDS_SOCAIL_CRYING               167
#define IDS_CTR_SOCAIL20                168
#define IDS_SOCAIL_STRETCHING           168
#define IDS_CTR_SOCAIL21                169
#define IDS_SOCAIL_SNEEZE               169
#define IDS_CTR_SOCAIL22                170
#define IDS_SOCAIL_WHIT_ME              170
#define IDS_CTR_SOCAIL23                171
#define IDS_SOCAIL_COME_HERE            171
#define IDS_CTR_SOCAIL24                172
#define IDS_SOCAIL_OK                   172
#define IDS_CTR_SOCAIL25                173
#define IDS_SOCAIL_DEEPLY               173
#define IDS_CTR_SOCAIL26                174
#define IDS_SOCAIL_ITIS_THERE           174
#define IDS_SOCAIL_THAT_WAY             174
#define IDS_CTR_SOCAIL27                175
#define IDS_SOCAIL_SIT_DOWN             175
#define IDS_CTR_HELP1                   176
#define IDS_HELP1                       176
#define IDS_CTR_HELP2                   177
#define IDS_HELP2                       177
#define IDS_CTR_HELP3                   178
#define IDS_HELP3                       178
#define IDS_CTR_HELP4                   179
#define IDS_HELP4                       179
#define IDS_CTR_HELP5                   180
#define IDS_HELP5                       180
#define IDS_CTR_HELP6                   181
#define IDS_HELP6                       181
#define IDS_CTR_HELP7                   182
#define IDS_HELP7                       182
#define IDS_CTR_HELP8                   183
#define IDS_HELP8                       183
#define IDS_CTR_HELP9                   184
#define IDS_HELP9                       184
#define IDS_CTR_HELP10                  185
#define IDS_HELP10                      185
#define IDS_CTR_HELP11                  186
#define IDS_HELP11                      186
#define IDS_CTR_HELP12                  187
#define IDS_HELP12                      187
#define IDS_CTR_HELP13                  188
#define IDS_HELP13                      188
#define IDS_CTR_HELP14                  189
#define IDS_HELP14                      189
#define IDS_CTR_HELP15                  190
#define IDS_HELP15                      190
#define IDS_CTR_HELP16                  191
#define IDS_HELP16                      191
#define IDS_CTR_HELP17                  192
#define IDS_HELP17                      192
#define IDS_CTR_HELP18                  193
#define IDS_HELP18                      193
#define IDS_CTR_HELP19                  194
#define IDS_HELP19                      194
#define IDS_CTR_HELP20                  195
#define IDS_HELP20                      195
#define IDS_CTR_HELP21                  196
#define IDS_HELP21                      196
#define IDS_CTR_HELP22                  197
#define IDS_HELP22                      197
#define IDS_MAIN1                       198
#define IDS_MAIN_TIME                   198
#define IDS_MAIN_DISPLAY_TIME           198
#define IDS_MAIN2                       199
#define IDS_MAIN_SPEEDHACK              199
#define IDS_MAIN3                       200
#define IDS_MAIN_UNABLE_EXECUTE         200
#define IDS_MAIN4                       201
#define IDS_MAIN_END_GAME               201
#define IDS_MAIN_EXIT_GAME              201
#define IDS_NK2DFRMAE1                  202
#define IDS_NK2D_REQUIRE_TRADE          202
#define IDS_NK2DFRAME2                  203
#define IDS_NK2D_REQUIRE_PARTY          203
#define IDS_UIMGR1                      204
#define IDS_UIMGR_UNABLE_SEKONG_SKILL   204
#define IDS_UIMGR2                      205
#define IDS_UIMGR_UNABLE_SEKONG         205
#define IDS_UIMGR3                      206
#define IDS_UIMGR_SEKONG_WORKING        206
#define IDS_UIMGR4                      207
#define IDS_UIMGR_NONE_GEMSTONE         207
#define IDS_UIMGR5                      208
#define IDS_UIMGR_SCARCE_KIT            208
#define IDS_UIMGR6                      209
#define IDS_UIMGR_FAIL_CONNECTION       209
#define IDS_UIMGR7                      210
#define IDS_UIMGR_SUCCEED_CONNECTION    210
#define IDS_UIMGR8                      211
#define IDS_UIMGR_BREAK_CONNECTION      211
#define IDS_UIMGR9                      212
#define IDS_UIMGR_SUCCEED_SEKONG        212
#define IDS_UIMGR10                     213
#define IDS_UIMGR_FAIL_SEKONG           213
#define IDS_UIMGR11                     214
#define IDS_UIMGR_COMPLETE_JEWEL        214
#define IDS_UIMGR12                     215
#define IDS_UIMGR_SUCCEED_UPGRADE       215
#define IDS_UIMGR13                     216
#define IDS_UIMGR_FAIL_UPGRADE          216
#define IDS_INVEN_RECOVERY_VATAL        217
#define IDS_INVER_RECOVERY_MANA         218
#define IDS_INVEN_RECOVERY_STA          219
#define IDS_INVEN_RECOVERY_ELECT        220
#define IDS_INVEN_ENABLE_SEGONG_LEVEL   221
#define IDS_INVEN_NEED_KIT_NUM          222
#define IDS_INVEN_UPGRADE_ITEM_LEVEL    223
#define IDS_INVEN_PRICE                 224
#define IDS_INVEN_SELLING_PRICE         225
#define IDS_INVEN_SCAREC_QUICKNESS      226
#define IDS_SKILL_NOR_ATT               227
#define IDS_SKILL_SCREEN_ROTATE         228
#define IDS_SKILL_REQUILE_LEVEL_SKILL   229
#define IDS_SKILL_SKILL_LEVEL           230
#define IDS_SKILL_STA_AND_DAMAGE        231
#define IDS_LOGIN_UNABLE_BLANK_STR      232
#define IDS_LOGIN_UNABLE_USE_STR        233
#define IDS_CRECHA_HAIR_22              234
#define IDS_CMD_GOST                    235
#define IDS_LOGIN_SELECT_SERVER         236
#define IDS_SELVILLAGE_SEL_LAGRAMIA     237
#define IDS_SELVILLAGE_SEL_AMPHITHEATER 238
#define IDS_SELVILLAGE_SEL_PLAZA        239
#define IDS_GATE_WORLD_MOVE             240
#define IDS_GATE_LAGRAMIA               241
#define IDS_GATE_AMPHITHEATER           242
#define IDS_GATE_PLAZA                  243
#define IDS_GATE_BULKAN                 244
#define IDS_GATE_KAI                    245
#define IDS_GATE_AID                    246
#define IDS_GATE_HUMAN                  247
#define IDS_UIMGR_SPOPUP_TITLE          248
#define IDS_UIMGR_SPOPUP_LINE_01        249
#define IDS_UIMGR_SPOPUP_LINE_02        250
#define IDS_UIMGR_SPOPUP_LINE_03        251
#define IDS_UIMGR_SPOPUP_LINE_04        252
#define IDS_UIMGR_SPOPUP_LINE_05        253
#define IDS_SKILL_MANA_DAMAGE           254
#define IDS_SKILL_DAMAGE_DEC_PHISICAL   255
#define IDS_SKILL_DOUBLE_SHOOT          256
#define IDS_INVEN_WRONG_RACE            257
#define IDS_INVEN_ONLY_BULKAN           258
#define IDS_INVEN_ONLY_KAI              259
#define IDS_INVEN_ONLY_AID              260
#define IDS_INVEN_ONLY_HUMAN            261
#define IDS_INVEN_GIFT01                262
#define IDS_INVEN_GIFT02                263
#define IDS_INVEN_GIFT03                264
#define IDS_INVEN_GIFT04                265
#define IDS_INVEN_THROW_UNABLE          266
#define IDS_INVEN_SEL_UNABLE            267
#define IDS_INVEN_EXCHA_UNABLE          268
#define IDS_INVEN_PLUS_ITEM             269
#define IDS_INVEN_JEWEL_ITEM            270
#define IDS_INTERCHA_UNABLE_CHANGE      271
#define IDS_INTERCHA_PUT_ITEM           272
#define IDS_UIMGR_GIFTBOX_ON            273
#define IDS_UIMGR_GIFTBOX_OFF           274
#define IDS_UIMGR_REALTIME_SYSTEM       275
#define IDS_CHECHA_BAD_NAME             276
#define IDS_INTERCHA_NOTEXGIST_ITEM     277
#define IDS_SHOP_PLUS_ITEM              278
#define IDS_SHOP_JEWEL_ITEM             279
#define IDS_INVEN_ALL_RECOVERY          280
#define IDS_SPECIAL_MAX_ATT_INC         281
#define IDS_SPECIAL_ATT_INC             282
#define IDS_SPECIAL_ATT_INC2            283
#define IDS_SPECIAL_HIT_ATT             284
#define IDS_SPECIAL_FATAL_ATT           285
#define IDS_SPECIAL_ATT_SPEED_INC       286
#define IDS_SPECIAL_ELECTRIC_MAGIC_DAMAGE 287
#define IDS_SPECIAL_FIRE_MAGIC_DAMAGE   288
#define IDS_SPECIAL_STONE_MAGIC_DAMAGE  289
#define IDS_SPECIAL_ALL_MAGIC_DAMAGE    290
#define IDS_SPECIAL_MAGIC_ATT_SPEED     291
#define IDS_SPECIAL_INT_DEC             292
#define IDS_SPECIAL_INT_NOT_EXIST       293
#define IDS_SPECIAL_DEX_DEC             294
#define IDS_SPECIAL_DEX_NOT_EXIST       295
#define IDS_SPECIAL_POWER_DEC           296
#define IDS_SPECIAL_POWER_NOT_EXIST     297
#define IDS_SPECIAL_LEVEL_DEC           298
#define IDS_SPECIAL_LEVEL_NOT_EXIST     299
#define IDS_SPECIAL_ALL_MAGIC_SHELD_INC 300
#define IDS_SPECIAL_ELECTRIC_MAGIC_SHELD_INC 301
#define IDS_SPECIAL_FIRE_MAGIC_SHELD_INC 302
#define IDS_SPECIAL_STONE_MAGIC_SHELD_INC 303
#define IDS_SPECIAL_FAL_SHELD_INC       304
#define IDS_SPECIAL_NEAR_SHELD_INC      305
#define IDS_SPECIAL_PHYSICAL_SHELD_INC  306
#define IDS_SPECIAL_VITAL_INC           307
#define IDS_SPECIAL_MANA_INC            308
#define IDS_SPECIAL_STA_INC             309
#define IDS_SPECIAL_ELECTRIC_INC        310
#define IDS_SPECIAL_READERSHIP_INC      311
#define IDS_SPECIAL_CON_INC             312
#define IDS_SPECIAL_DEX_INC             313
#define IDS_SPECIAL_POWER_INC           314
#define IDS_SPECIAL_INT_INC             315
#define IDS_SPECIAL_MONEY_INC           316
#define IDS_SPECIAL_EXP_INC             317
#define IDS_SPECIAL_ITEM_INC            318
#define IDS_SPECIAL_REPOINT_ABLE        319
#define IDS_INVEN_KAI_MANA_USE          320
#define IDS_INVEN_QUICK01               321
#define IDS_INVEN_QUICK02               322
#define IDS_SPECIAL_MIN_ATT_INC         323
#define IDS_WAREHOUSE_BLANK             324
#define IDS_WAREHOUSE_NOTNUM            325
#define IDS_WAREHOUSE_NOT100            326
#define IDS_WAREHOUSE_NOT0              327
#define IDS_WAREHOUSE_NOTENOUGH         328
#define IDS_INVEN_PLUSE5_WORRING        329
#define IDS_SKILL_IRON_SKIN             330
#define IDS_WAREHOUSE_INMONEY           331
#define IDS_WAREHOUSE_OUTMONEY          332
#define IDS_EXCHANGE_UNABLE_ITEM        333
#define IDS_GATE_SHAILON                334
#define IDS_SKILL_INC_EPOWER            335
#define IDS_SKILL_INC_RANGE             336
#define IDS_SKILL_WASTE_EPOWER          337
#define IDS_SKILL_10SEC_WASTE_EPOWER    338
#define IDS_SKILL_VISION_DIST           339
#define IDS_GAMBLE_INFO01               340
#define IDS_GAMBLE_INFO02               341
#define IDS_GAMBLE_INFO03               342
#define IDS_GAMBLE_INFO04               343
#define IDS_GAMBLE_INFO05               344
#define IDS_GAMBLE_INFO06               345
#define IDS_GAMBLE_INFO07               346
#define IDS_GAMBLE_INCLUDE_DIFF_CHIP    347
#define IDS_GAMBLE_INCLUDE_NOTCHIP      348
#define IDS_GAMBLE_NEED_5CHIP           349
#define IDS_GAMBLE_NEED_1CHIP           350
#define IDS_INTERCHA_NOT_ENOUGH_MONEY   351
#define IDS_INTERCHA_NEED_MONEY         352
#define IDS_INTERCHA_NORMAL_ITEM        353
#define IDS_UIMGR_MOVE_GEM              354
#define IDS_CRECHA_BADNAME              355
#define IDS_NK2D_REQUIRE_REFINE         356
#define IDS_REFINE_INPUT_MONEY          357
#define IDS_REFINE_ERROR_0              358
#define IDS_REFINE_ERROR_1              359
#define IDS_REFINE_ERROR_2              360
#define IDS_REFINE_ERROR_3              361
#define IDS_REFINE_ERROR_4              362
#define IDS_REFINE_ERROR_5              363
#define IDS_REFINE_ERROR_6              364
#define IDS_UIMGR_FAIL_ADDOP            365
#define IDS_UIMGR_ADDOP                 366
#define IDS_UIMGR_DOWNGRADE_OP          367
#define IDS_REFINE_REFINNING            368
#define IDS_SPECIAL_DOWN_MAGIC_DAM      369
#define IDS_SPECIAL_UP_MAGIC_DAM        370
#define IDS_SPECIAL_INC_BASEMAGIC_DAM   371
#define IDS_SPECIAL_INC_MAGIC_DAM       372
#define IDS_SPECIAL_HIT_MAGIC           373
#define IDS_SPECIAL_FATAL_MAGIC         374
#define IDS_SPECIAL_INC_SPEED           375
#define IDS_SPECIAL_INC_SPECIAL_DAM     376
#define IDS_SPECIAL_INC_DEF             377
#define IDS_SPECIAL_INC_DEF2            378
#define IDS_SPECIAL_INC_SPECIAL_DEF     379
#define IDS_CMD_SAY_TO                  380
#define IDS_CMD_GUILD_TO                381
#define IDS_CMD_PARTY_TO                382
#define IDS_BOTTOM_NC                   383
#define IDS_BOTTOM_EX                   384
#define IDS_BOTTOM_REFINE               385
#define IDS_BOTTOM_PARTY                386
#define IDS_GATE_LOST_REALM             387
#define IDS_GATE_SALANOS_HARBOR         388
#define IDS_GATE_NEORHASA_CAMP          389
#define IDS_UIMGR_MUTANT                390
#define IDS_NOT_DECIDE                  391
#define IDS_WAR_NOT_DECIDE              391
#define IDS_WAR_REQUEST_LIME            392
#define IDS_WAR_NEED_REQUEST            393
#define IDS_WAR_ALREADY_REQUEST         394
#define IDS_WAR_NOT_TIME_YET            395
#define IDS_WAR_WHEN                    396
#define IDS_WAR_DECIDE_DATE_TIME        397
#define IDS_WAR_NOT_REQUEST_YET         398
#define IDS_WAR_TERM                    399
#define IDS_TAX_WITHDRAWAL              400
#define IDS_TAX_NO_BLANK                401
#define IDS_TAX_NO_SPECIAL_CHAR         402
#define IDS_TAX_SCARCE_MONEY            403
#define IDS_GUARDTOWER_ATT_MODE_MULTI   404
#define IDS_GUARDTOWER_ATT_MODE_DAMAGE  405
#define IDS_GUARDTOWER_ATT_MODE_NORMAL  406
#define IDS_GUARDTOWER_TOP_LEVEL_NORMAL 407
#define IDS_GUARDTOWER_TOP_LEVEL_ALITTLE_HIGH 408
#define IDS_GUARDTOWER_TOP_LEVEL_HIGH   409
#define IDS_GUARDTOWER_TOP_LEVEL_VERYHIGH 410
#define IDS_GUARDTOWER_TOP_NAME_FIRE_NORMAL 411
#define IDS_GUARDTOWER_TOP_NAME_FIRE_ADVANCE 412
#define IDS_GUARDTOWER_TOP_NAME_FIRE_TOWER 413
#define IDS_GUARDTOWER_TOP_NAME_FIRE_GREATFIRE 414
#define IDS_GUARDTOWER_TOP_NAME_LIGHT_NORMAL 415
#define IDS_GUARDTOWER_TOP_NAME_LIGHT_ADVANCE 416
#define IDS_GUARDTOWER_TOP_NAME_LIGHT_TOWER 417
#define IDS_GUARDTOWER_TOP_NAME_LIGHT_GREATLIGHT 418
#define IDS_GUARDTOWER_TOP_NAME_STONE_NORMAL 419
#define IDS_GUARDTOWER_TOP_NAME_STONE_ADVANCE 420
#define IDS_GUARDTOWER_TOP_NAME_STONE_TOWER 421
#define IDS_GUARDTOWER_TOP_NAME_STONE_GREATLIGHT 422
#define IDS_GUARDTOWER_BODY_MODE_CLAY   423
#define IDS_GUARDTOWER_BODY_MODE_STONE  424
#define IDS_GUARDTOWER_BODY_MODE_STEEL  425
#define IDS_GUARDTOWER_BODY_LEVEL_NORMAL 426
#define IDS_GUARDTOWER_BODY_LEVEL_MIDDLE 427
#define IDS_GUARDTOWER_BODY_LEVEL_VERYHIGH 428
#define IDS_GUARDTOWER_SHIELD_LEVEL_NONE 429
#define IDS_GUARDTOWER_SHIELD_LEVEL_NORMAL 430
#define IDS_GUARDTOWER_SHIELD_LEVEL_ALITTLESTRONG 431
#define IDS_GUARDTOWER_SHIELD_LEVEL_STRONG 432
#define IDS_GUARDTOWER_SHIELD_LEVEL_VERYSTRONG 433
#define IDS_WARINFO_POINT1              434
#define IDS_WARINFO_POINT2              435
#define IDS_WARINFO_POINT3              436
#define IDS_WARINFO_SEC                 437
#define IDS_UIMGR_CRISTAL_MOVE_MASTERROOM 438
#define IDS_CHANGHAIR_PRICE             439
#define IDS_CMD_NOTYET_EGG              440
#define IDS_CMD_LIVE_TIME               441
#define IDS_CMD_UNABLE_BUY              442
#define IDS_BOTTOM_WHISPER_OFF          443
#define IDS_BOTTOM_WHISPER_ON           444
#define IDS_INVEN_DAM_REFLECTION        445
#define IDS_INVEN_VITAL                 446
#define IDS_INVEN_ATT_RANGE             447
#define IDS_INVEN_ATT_MELEE             448
#define IDS_INVEN_DEF_RANGE             449
#define IDS_INVEN_DEF_MELEE             450
#define IDS_INVEN_SPEED                 451
#define IDS_INVEN_COLLECTION            452
#define IDS_INVEN_EXP_BUY               453
#define IDS_INVEN_EXP_RESTORE           454
#define IDS_INVEN_EXP_RESUME            455
#define IDS_IMPOSSIBLE_WARESHOUSE       456
#define IDS_PEICESHOP_NOTEXIST          457
#define IDS_PETKEEP_TIME                458
#define IDS_PETKEEP_NOTENOUGH_MONEY     459
#define IDS_PETSHOP_90LEVEL             460
#define IDS_PETSHOP_NOTENOUGH_MONEY     461
#define IDS_PETSHOP_UNABLE_BUY          462
#define IDS_TOP_PET_NOTEXIST            463
#define IDS_TOP_PET_NOTYET              464
#define IDS_TOP_PET_KEEPING             465
#define IDS_GWAR_INPUT_NAME             466
#define IDS_GWAR_UNABLE_EMPTY           467
#define IDS_GWAR_INPUT_PAY              468
#define IDS_GWAR_WRONG_MONEY            469
#define IDS_GWAR_MAX_PAY                470
#define IDS_GWAR_OTHER_NAME             471
#define IDS_GWAR_UNBLAE_EMPTY2          472
#define IDS_UIMGR_PET_INPUT_NAME        473
#define IDS_UIMGR_PET_MAX_STR           474
#define IDS_UIMGR_PET_UNABLE_EMPTY      475
#define IDS_UIMGR_PET_UNABLE_STR        476
#define IDS_UIMGR_PET_NOTEXIST          477
#define IDS_UIMGR_PET_UNABLE_NAME       478
#define IDS_UIMGR_PET_UNABLE_NAME2      479
#define IDS_UIMGR_PET_NOTENOUGHT_LEVEL  480
#define IDS_UIMGR_PET_MAKE_NAME         481
#define IDS_UIMGR_PET_PRICE             482
#define IDS_UIMGR_PET_PRICE2            483
#define IDS_UIMGR_PET_NOTUSE            484
#define IDS_UIMGR_CHASEX_BOY_GIRL       485
#define IDS_UIMGR_CHASEX_GIRL_BOY       486
#define IDS_UIMGR_CHASEX_EVENT_TITLE    487
#define IDS_UIMGR_CHASEX_TEXT0          488
#define IDS_UIMGR_CHASEX_TEXT0_1        489
#define IDS_UIMGR_CHASEX_TEXT1          490
#define IDS_UIMGR_CHASEX_TEXT2          491
#define IDS_UIMGR_PET_SRVMSG_NOTEXIST   492
#define IDS_UIMGR_PET_SRVMSG_NOT_YET    493
#define IDS_UIMGR_PET_SRVMSG_KEEPING    494
#define IDS_UIMGR_GWAR_ALREADY          495
#define IDS_UIMGR_GWAR_REQ              496
#define IDS_UIMGR_GWAR_REQ2             497
#define IDS_UIMGR_GWAR_CONNECT_CLOSE    498
#define IDS_UIMGR_GWAR_CANCEL           499
#define IDS_UIMGR_GWAR_OTHER            500
#define IDS_UIMGR_GWAR_AGREE_BATTLE     501
#define IDS_UIMGR_GWAR_ALREADY_REQ      502
#define IDS_UIMGR_GWAR_NOTEXIST         503
#define IDS_UIMGR_GWAR_END              504
#define IDS_UIMGR_GWAR_AGREE            505
#define IDS_PETLEV_NOTENOUGH_MONEY      506
#define IDS_PETLEV_NOTENOUGH_LEVEL      507
#define IDS_PETLEV_COMPLETE             508
#define IDS_PETLEV_PRE_BUY              509
#define IDS_PETLEV_PRE_REVIVE           510
#define IDS_PETLEV_PRE_TAKE             511
#define IDS_INVEN_COMPOS_LEVEL          512
#define IDS_INVEN_MIN_LEVEL             513
#define IDS_INVEN_ATT                   514
#define IDS_INVEN_DEMOL                 515
#define IDS_INVEN_LASTING               516
#define IDS_INVEN_STAMINA               517
#define IDS_INVEN_USE_STAMINA           518
#define IDS_INVEN_DURATION              519
#define IDS_INVEN_CUTTING_RATE          520
#define IDS_INVEN_STONE_RATE            521
#define IDS_INVEN_STUN_RATE             522
#define IDS_INVEN_INC_DURAION           523
#define IDS_INVEN_CANNON_BULLET         524
#define IDS_INVEN_FIREGUN_BULLET        525
#define IDS_INVEN_LASER_BULLET          526
#define IDS_INVEN_MINE_THRAW_BULLET     527
#define IDS_INVEN_S_THRAW_BULLET        528
#define IDS_INVEN_M_THRAW_BULLET        529
#define IDS_INVEN_NUCLEAR_BULLET        530
#define IDS_INVEN_CHARGE_RATE           531
#define IDS_INVEN_SUMMONS_C             532
#define IDS_INVEN_SUMMONS_AJ            533
#define IDS_INVEN_SUMMONS_DG            534
#define IDS_INVEN_SUMMONS_GS            535
#define IDS_INVEN_SUMMONS_DK            536
#define IDS_INVEN_SUMMONS_TIGER         537
#define IDS_INVEN_REMAIN_TIME           538
#define IDS_INVEN_USE_MANA              539
#define IDS_INVEN_ASSEMB_RADAR          540
#define IDS_INVEN_ASSEMB_HARD           541
#define IDS_INVEN_ASSEMB_PURGE          542
#define IDS_INVEN_ASSEMB_VOLT           543
#define IDS_INVEN_ASSEMB_VOLCANIC       544
#define IDS_INVEN_ASSEMB_STONE          545
#define IDS_INVEN_ASSEMB_COLD           546
#define IDS_INVEN_ASSEMB_ELEC_HIT       547
#define IDS_INVEN_ASSEMB_ELEC_SUCTION   548
#define IDS_INVEN_ASSEMB_ELEC_DOUBLE    549
#define IDS_INVEN_ASSEMB_ATOM           550
#define IDS_INVEN_ASSEMB_GAB            551
#define IDS_INVEN_ASSEMB_GAB2           552
#define IDS_INVEN_ASSEMB_INTEG          553
#define IDS_INVEN_ASSEMB_INTEG2         554
#define IDS_INVEN_DAM_DURAITON          555
#define IDS_INVEN_RATE_BLAST            556
#define IDS_INVEN_DAM_MINE              557
#define IDS_INVEN_GATHER_PARTS          558
#define IDS_INVEN_NUM_BULLET            559
#define IDS_INVEN_USE_ELEC              560
#define IDS_INVEN_NUM_SLOT              561
#define IDS_INVEN_DAM_MAGIC             562
#define IDS_INVEN_RATE_COLD             563
#define IDS_INVEN_RATE_CHAOS            564
#define IDS_INVEN_DEATH                 565
#define IDS_INVEN_REMAIN_MAGIC          566
#define IDS_INVEN_DIST_ATT              567
#define IDS_INVEN_REC_SCROLL_4          568
#define IDS_INVEN_REC_SCROLL_5          569
#define IDS_INVEN_REC_SCROLL_6          570
#define IDS_INVEN_SCROLL_0              571
#define IDS_INVEN_SCROLL_1              572
#define IDS_INVEN_SCROLL_2              573
#define IDS_INVEN_SCROLL_3              574
#define IDS_INVEN_SCROLL_4              575
#define IDS_INVEN_SCROLL_5              576
#define IDS_INVEN_SCROLL_6              577
#define IDS_INVEN_SCROLL_7              578
#define IDS_INVEN_SCROLL_8              579
#define IDS_INVEN_SCROLL_9              580
#define IDS_INVEN_SCROLL_10             581
#define IDS_INVEN_SCROLL_11             582
#define IDS_INVEN_SCROLL_12             583
#define IDS_INVEN_SCROLL_13             584
#define IDS_INVEN_SCROLL_14             585
#define IDS_INVEN_SCROLL_15             586
#define IDS_INVEN_SCROLL_16             587
#define IDS_INVEN_SCROLL_17             588
#define IDS_INVEN_EMPTY                 589
#define IDS_INVEN_ORDER                 590
#define IDS_INVEN_SCROLL                591
#define IDS_INVEN_ANCIENT_LEV           592
#define IDS_INVEN_ABLE_SHOW_MON         593
#define IDS_INVEN_REMOVE_HARDB          594
#define IDS_INVEN_REMOVE_PURGE          595
#define IDS_INVEN_INC_VOLT              596
#define IDS_INVEN_INC_VOLCANIC          597
#define IDS_INVEN_INC_STONE             598
#define IDS_INVEN_INC_COLD              599
#define IDS_INVEN_REFLECTION_DAM        600
#define IDS_INVEN_DEC_ELEC              601
#define IDS_INVEN_INC_ATT               602
#define IDS_INVEN_TELEPORT              603
#define IDS_INVEN_INVISIBLE             604
#define IDS_INVEN_VISIBLE               605
#define IDS_INVEN_INC_RESISTANT         606
#define IDS_INVEN_REMOVE_CURSE          607
#define IDS_INVEN_ASSEMB_PARTS          608
#define IDS_INVEN_RECHARGE_WAND         609
#define IDS_INVEN_RATE_STUN             610
#define IDS_INVEN_DEC_VIATL             611
#define IDS_INVEN_RATE_FREEZE           612
#define IDS_INVEN_PROTECTION            613
#define IDS_INVEN_RESIS_VOLT            614
#define IDS_INVEN_RESIS_VOLCANIC        615
#define IDS_INVEN_RESIS_STONE           616
#define IDS_INVEN_RESIS_COLD            617
#define IDS_SKILL_INC_ATT               618
#define IDS_SKILL_INC_ATT2              619
#define IDS_SKILL_INC_RESIS             620
#define IDS_SKILL_RATE_REMOVE           621
#define IDS_SKILL_REMOVE_PURGE          622
#define IDS_SKILL_DAM_DIVISION          623
#define IDS_SKILL_KEEP_TIME             624
#define IDS_SKILL_REMOVE_MENTAL         625
#define IDS_SKILL_REMOVE_SKILL          626
#define IDS_SKILL_INC_DEF               627
#define IDS_SKILL_SUCTION_DAM           628
#define IDS_SKILL_DEF_MON_DEF           629
#define IDS_SKILL_RATE_HARDB            630
#define IDS_SKILL_INC_ATT3              631
#define IDS_SKILL_INC_SUMMONS_TIME      632
#define IDS_SKILL_DEC_MANA_USE          633
#define IDS_PRODUCT_INFO_0              634
#define IDS_PRODUCT_INFO_1              635
#define IDS_PRODUCT_INFO_2              636
#define IDS_PRODUCT_INFO_3              637
#define IDS_PRODUCT_INFO_4              638
#define IDS_PRODUCT_INFO_5              639
#define IDS_PRODUCT_INFO_6              640
#define IDS_PRODUCT_INFO_7              641
#define IDS_PRODUCT_INFO_8              642
#define IDS_PRODUCT_INFO_9              643
#define IDS_PRODUCT_INFO_10             644
#define IDS_PRODUCT_INFO_11             645
#define IDS_PRODUCT_INFO_12             646
#define IDS_PRODUCT_INFO_13             647
#define IDS_PRODUCT_INFO_14             648
#define IDS_PRODUCT_INFO_15             649
#define IDS_PRODUCT_INFO_16             650
#define IDS_PRODUCT_INFO_17             651
#define IDS_PRODUCT_INFO_18             652
#define IDS_PRODUCT_INFO_19             653
#define IDS_PRODUCT_INFO_20             654
#define IDS_PRODUCT_INFO_21             655
#define IDS_PRODUCT_INFO_22             656
#define IDS_PRODUCT_INFO_23             657
#define IDS_PRODUCT_INFO_24             658
#define IDS_PRODUCT_INFO_25             659
#define IDS_PRODUCT_INFO_26             660
#define IDS_PRODUCT_INFO_27             661
#define IDS_PRODUCT_INFO_28             662
#define IDS_PRODUCT_INFO_29             663
#define IDS_PRODUCT_INFO_30             664
#define IDS_PRODUCT_INFO_31             665
#define IDS_PRODUCT_INFO_32             666
#define IDS_PRODUCT_INFO_33             667
#define IDS_PRODUCT_INFO_34             668
#define IDS_PRODUCT_INFO_35             669
#define IDS_PRODUCT_INFO_36             670
#define IDS_PRODUCT_INFO_37             671
#define IDS_PRODUCT_INFO_38             672
#define IDS_PRODUCT_CONFIRM             673
#define IDS_PRODUCT_ONLY_HUMAN          674
#define IDS_PRODUCT_NOTENOUGH_LEV       675
#define IDS_INVEN_RATE_CHAOS2           676
#define IDS_INVEN_DEF_70                677
#define IDS_CMD_PET_NAME                678
#define IDS_SOCAIL_CLAP3                679
#define IDS_BOTTOM_ROT_CAM              680
#define IDS_BOTTOM_ATT_NOR              681
#define IDS_BOTTOM_CHANNEL              682
#define IDS_BOTTOM_INFO_CHARACTER       683
#define IDS_BOTTOM_HAVINGS              684
#define IDS_BOTTOM_SKILL                685
#define IDS_BOTTOM_PET                  686
#define IDS_BOTTOM_MAP                  687
#define IDS_BOTTOM_HELP                 688
#define IDS_BOTTOM_INFO_PARTY           689
#define IDS_BOTTOM_EXIT                 690
#define IDS_BOTTOM_EXCH                 691
#define IDS_BOTTOM_INFO_REFINE          692
#define IDS_BOTTOM_G_OUT                693
#define IDS_BOTTOM_G_OUT_WARNING        694
#define IDS_GATE_SEARUSTE               695
#define IDS_GATE_DEKADUNE               696
#define IDS_GATE_DEKALEN                697
#define IDS_GATE_SIRUSTE                698
#define IDS_CMD_PREE_PK_ON              699
#define IDS_CMD_PREE_PK_OFF             700
#define IDS_SPECIAL_TAKE                701
#define IDS_BOTTOM_SALE                 702
#define IDS_BOTTOM_WHISPER              703
#define IDS_MAP_DEKADUNE                704
#define IDS_MAP_DEKALEN                 705
#define IDS_SHOP_CELL_WARNING           706
#define IDS_HELP23                      707
#define IDS_LSHIFT_MOOD_0               708
#define IDS_LSHIFT_MOOD_1               709
#define IDS_LSHIFT_MOOD_2               710
#define IDS_LSHIFT_MOOD_3               711
#define IDS_INVEN_MASUCK_DROP           712
#define IDS_INVEN_SPECIALITEM_DROP      713
#define IDS_MAP_ZOO                     714
#define IDS_MAP_VILL                    715
#define IDS_MAP_ZONE                    716
#define IDS_MAP_PHAROS                  717
#define IDS_MAP_LAGRAMIA                718
#define IDS_SHOP_MASUCK_CELL            719
#define IDS_SHOP_SPECIALITEM_CELL       720
#define IDS_CMD_FAIL_RING               721
#define IDS_BOTTOM_QUICKSLOT            722
#define IDS_INVEN_SUMMONS_ALEN          723
#define IDS_INVEN_REQ_LEVEL             724
#define IDS_INVEN_PHYSCAL_DAM           725
#define IDS_INVEN_DAM_REFLECTION2       726
#define IDS_INVEN_UPGRADE_LEVEL         727
#define IDS_INVEN_LEFT_CNT              728
#define IDS_INVEN_PRIZ_RATE             729
#define IDS_INVEN_PRIZ_RATE2            730
#define IDS_INVEN_EXPECT_PRICE          731
#define IDS_INVEN_WARNING_RING          732
#define IDS_EVENTACIENT_WARNING_RING    733
#define IDS_EVENTACIENT_TOY             734
#define IDS_EVENTACIENT_HAVE_ITEM       735
#define IDS_EVENTACIENT_HAVE_PLUSEITEM  736
#define IDS_EVENTACIENT_ONLYONE         737
#define IDS_EVENTACIENT_ERROR           738
#define IDS_EVENTACIENT_FAIL            739
#define IDS_EVENTACIENT_HAVE_LAIM2      740
#define IDS_PRODUCT_RECEPTION_MACHINE   741
#define IDS_PRODUCT_KIT_INFO            742
#define IDS_QUEST_INFO_0                743
#define IDS_QUEST_INFO_1                744
#define IDS_QUEST_INFO_2                745
#define IDS_QUEST_NO_DATA               746
#define IDS_QUEST_GET_EXP               747
#define IDS_QUEST_GET_LAIM              748
#define IDS_QUEST_NO_MACHINE            749
#define IDS_QUEST_CONFIRM_LEVEL         750
#define IDS_QUEST_UNABLE_MACHINE        751
#define IDS_QUEST_NOT_RECEIVE           752
#define IDS_SPECIAL_INC_COUNT           753
#define IDS_SPECIAL_INC_CRITICAL        754
#define IDS_SPECIAL_INC_ACCUMUL         755
#define IDS_SPECIAL_INC_BOLCANIC        756
#define IDS_SPECIAL_INC_STONE           757
#define IDS_SPECIAL_INC_COLD            758
#define IDS_SPECIAL_INC_TOTAL           759
#define IDS_SPECIAL_INC_SKILLTIME       760
#define IDS_SPECIAL_INC_RECOVER         761
#define IDS_UIMGR_CURSED                762
#define IDS_QUEST_REALLY_ABANDOM        763
#define IDS_QUEST_ITEM_NOT_MATCH        764
#define IDS_CANNOT_WEAR_ITEM            765
#define IDS_CHECK_EVENT_ITEM            766
#define IDS_HAVE_MASUK                  767
#define IDS_EXCHANGE_UNIFORM_SET        768
#define IDS_PET_EARTH_RING              769
#define IDS_PET_EARTH_RING_ITEM1        770
#define IDS_PET_EARTH_RING_ITEM2        771
#define IDS_PET_SKY_RING                772
#define IDS_PET_SKY_RING_ITEM1          773
#define IDS_PET_SKY_RING_ITEM2          774
#define IDS_PET_SKY_RING_ITEM3          775
#define IDS_HAVE_NOITEM                 776
#define IDS_CHECK_ITEM                  777
#define IDS_CHECK_ITEM_KIND             778
#define IDS_CHECK_ITEM_SET              779
#define IDS_SUCCESS_EXCHANGE_ITEM       780
#define IDS_EXCHANGE_ITEM_GET_LAIM      781
#define IDS_INPUT_PASSWORD              782
#define IDS_PLATINUM_PLACE_ITEM         783
#define IDS_CANNOT_PLACE_EMERALD        784
#define IDS_PLATINUM_ITEM_MISMATCH      785
#define IDS_CHECK_ITEM_COUNT            786
#define IDS_CHECK_PLATINUM_COUNT        787
#define IDS_PLATINUM_DEFICIT_LAIM       788
#define IDS_PLATINUM_FAIL_REFINE        789
#define IDS_PLATINUM_SUCCESS_REFINE_WEAPON 790
#define IDS_PLATINUM_SUCCESS_REFINE_ARMOR 791
#define IDS_ERROR                       792
#define IDS_FAIL_PRODUCT                793
#define IDS_PET_TRANSFER                794
#define IDS_GUILD_REQUEST               795
#define IDS_GUILD_SURRENDER             796
#define IDS_SUPPORT_MODE                797
#define IDS_LONG_RANGE_MODE             798
#define IDS_PET_PRODUCT_CAPSULE1        799
#define IDS_PET_PRODUCT_NEED_LEVEL1     800
#define IDS_PET_PRODUCT_CAPSULE2        801
#define IDS_PET_PRODUCT_NEED_LEVEL2     802
#define IDS_PET_PRODUCT_CAPSULE3        803
#define IDS_PET_PRODUCT_NEED_LEVEL3     804
#define IDS_PET_PRODUCT_CAPSULE4        805
#define IDS_PET_PRODUCT_NEED_LEVEL4     806
#define IDS_PET_PRODUCT_CAPSULE5        807
#define IDS_PET_PRODUCT_NEED_LEVEL5     808
#define IDS_PET_PRODUCT_CAPSULE6        809
#define IDS_PET_PRODUCT_NEED_LEVEL6     810
#define IDS_PET_PRODUCT_PETLEVEL1       811
#define IDS_PET_PRODUCT_PETEXP1         812
#define IDS_PET_PRODUCT_PETLEVEL2       813
#define IDS_PET_PRODUCT_PETEXP2         814
#define IDS_PET_PRODUCT_PETLEVEL3       815
#define IDS_PET_PRODUCT_PETEXP3         816
#define IDS_PET_PRODUCT_PETLEVEL4       817
#define IDS_PET_PRODUCT_PETEXP4         818
#define IDS_PET_PRODUCT_PETLEVEL5       819
#define IDS_PET_PRODUCT_PETEXP5         820
#define IDS_PET_PRODUCT_PETLEVEL6       821
#define IDS_PET_PRODUCT_PETEXP6         822
#define IDS_GATE_WHITEHORN              823
#define IDS_INVEN_INC_DURAION_CHAKRAM   824
#define IDS_CANNOT_USE_IN_PEACEZONE     825
#define IDS_MAP_SEAROOST4               826
#define IDS_SPECIAL_INC_ABS_DAMAGE      827
#define IDS_SPECIAL_INC_AVOIDANCE       828
#define IDS_USER_CHECK1                 829
#define IDS_USER_CHECK2                 830
#define IDS_INSERT_NUM10_1              831
#define IDS_INSERT_NUM10_2              832
#define IDS_UP20                        833
#define IDS_CANNOT_CASTLE1              834
#define IDS_CANNOT_CASTLE2              835
#define IDS_51LEV_RESTRICT              836
#define IDS_1011LEV_RESTRICT            837
#define IDS_151LEV_RESTRICT             838
#define IDS_RESI_8                      839
#define IDS_MELEE_AVOID10               840
#define IDS_SP_MAGIC_AVOID30            841
#define IDS_MELEE_AVOID20               842
#define IDS_SP_MAGIC_AVOID10            843
#define IDS_51LEV_ITEM_RESTRICT         844
#define IDS_NOTUSE                      845
#define IDS_USE                         846
#define IDS_FULLSCREEN                  847
#define IDS_WINDOWS                     848
#define IDS_NOTDISPLAY                  849
#define IDS_ONLYCHAR                    850
#define IDS_ONLYPLAYER                  851
#define IDS_ALLPLAYER                   852
#define IDS_OPTION_1                    853
#define IDS_OPTION_2                    854
#define IDS_OPTION_3                    855
#define IDS_OPTION_4                    856
#define IDS_OPTION_5                    857
#define IDS_OPTION_6                    858
#define IDS_OPTION_7                    859
#define IDS_OPTION_9                    860
#define IDS_OPTION_10                   861
#define IDS_OPTION_11                   862
#define IDS_OPTION_12                   863
#define IDS_OPTION_13                   864
#define IDS_NEED_1                      865
#define IDS_NEED_2                      866
#define IDS_NEED_3                      867
#define IDS_NEED_4                      868
#define IDS_NEED_5                      869
#define IDS_NEED_6                      870
#define IDS_NOT_SET                     871
#define IDS_PLACE_TRANS                 872
#define IDS_CANNOT_TRANS                873
#define IDS_NOTSET_PLACE                874
#define IDS_CANNOT_SPACE                876
#define IDS_INVALID_MONEY               877
#define IDS_MONEY_1000                  878
#define IDS_INVALID_REINPUT             879
#define IDS_NOT_ENOUGH                  880
#define IDS_MONEY_RECEIPT               881
#define IDS_MONEY_PAYMENT               882
#define IDS_SOSCIAL_N1                  883
#define IDS_SOSCIAL_N2                  884
#define IDS_SOSCIAL_N3                  885
#define IDS_SOSCIAL_N4                  886
#define IDS_SOSCIAL_N5                  887
#define IDS_SOSCIAL_N6                  888
#define IDS_SOSCIAL_N7                  889
#define IDS_SOSCIAL_N8                  890
#define IDS_SOSCIAL_N9                  891
#define IDS_SOSCIAL_N10                 892
#define IDS_SOSCIAL_N11                 893
#define IDS_SOSCIAL_N12                 894
#define IDS_SOSCIAL_N13                 895
#define IDS_SOSCIAL_N14                 896
#define IDS_SOSCIAL_N15                 897
#define IDS_SOSCIAL_N16                 898
#define IDS_SOSCIAL_N17                 899
#define IDS_SOSCIAL_N18                 900
#define IDS_SOSCIAL_N19                 901
#define IDS_SOSCIAL_N20                 902
#define IDS_SOSCIAL_N21                 903
#define IDS_SOSCIAL_N22                 904
#define IDS_SOSCIAL_N23                 905
#define IDS_SOSCIAL_N24                 906
#define IDS_SOSCIAL_N25                 907
#define IDS_SOSCIAL_N26                 908
#define IDS_SOSCIAL_N27                 909
#define IDS_WATCH_ITEM                  910
#define IDS_LOST_OPTION                 911
#define IDS_TEAM_BATTLE                 912
#define IDS_SURVIVAL_BATTLE             913
#define IDS_MONSTER_SURVIVAL            914
#define IDS_NOMAL_ROOM                  915
#define IDS_DEATH_MATCH                 916
#define IDS_MATRIX_ROOM                 917
#define IDS_MOVE_CRYSTAL_CASTLE         918
#define IDS_MOVE_FLAG_N                 919
#define IDS_MOVE_FLAG_E                 920
#define IDS_MOVE_FLAG_W                 921
#define IDS_MOVE_FLAG_S                 922
#define IDS_KIN_LA                      923
#define IDS_DELETE_BAD                  924
#define IDS_NOTFIND_CHAR                925
#define IDS_CANNOT_CONNECT              926
#define IDS_TEAMBATTLE                  927
#define IDS_SURVIVAL                    928
#define IDS_CANT_CRE_MATRIX             932
#define IDS_CANT_CRE_GAME               933
#define IDS_CANT_DEL_MATRIX             934
#define IDS_CANT_DEL_GAME               935
#define IDS_INVEN_ITEM_SLAYER           943
#define IDS_INVEN_ITEM_CHAKRAM          944
#define IDS_INVEN_ITEM_BOOK             945
#define IDS_INVEN_ITEM_WAND             946
#define IDS_INVEN_ITEM_S_EQUIP          947
#define IDS_INVEN_ITEM_L_EQUIP          948
#define IDS_INVEN_ITEM_DECARDI_BRACELET 949
#define IDC_DEVICE_COMBO                1000
#define IDC_MODE_COMBO                  1001
#define IDC_LIST_COMM                   1001
#define IDC_LIST_OBJ1                   1002
#define IDC_OBJ_TAB                     1003
#define IDC_LIST_OBJ2                   1004
#define IDC_EDIT_ID                     1004
#define IDC_EDIT_PASS                   1005
#define IDC_EDITSVR                     1006
#define IDC_EDITCLI                     1007
#define IDC_TAB1                        1008
#define IDC_CLOSE                       1009
#define IDC_LIST_STRING                 1011
#define IDC_WINDOWED_CHECKBOX           1012
#define IDC_SELECTED                    1012
#define IDC_STEREO_CHECKBOX             1013
#define IDC_CHK_SILENCE                 1013
#define IDC_FULLSCREEN_TEXT             1014
#define ID_LIME                         1014
#define ID_EXP                          1015
#define ID_DAMAGE                       1016
#define IDC_POINTLOG_LIST               1017
#define ID_POINTLOG_PAUSE               1018
#define IDC_BTN_SAVE_CLI                1018
#define ID_POINTLOG_ALL_SAVE            1019
#define IDC_BUTTON1                     1025
#define IDC_BUTTON3                     1026
#define IDC_BTN_SAVE_SVR                1026
#define IDC_BUTTON2                     1044
#define IDC_BUTTON4                     1046
#define IDPAUSE                         1048
#define IDC_LIST_COMM2                  1049
#define IDSRH_SVR                       1050
#define IDSRH_CLI                       1051
#define IDS_LIMIT_LEVEL275              1070
#define IDM_EXIT                        40001
#define IDM_ABOUT                       40002
#define IDM_TOGGLESTART                 40003
#define IDM_CHANGEDEVICE                40004
#define IDM_SINGLESTEP                  40005
#define IDM_TOGGLEFULLSCREEN            40006
#define MENU_FLAT                       40007
#define MENU_FLAT_SHADING               40007
#define MENU_GOURAUD                    40008
#define MENU_GOURAUD_SHADING            40008
#define IDM_LOADTEXTURE                 40009
#define MENU_LIGHT_SOURCES              40010
#define IDM_WIREFRAME                   40011
#define IDM_PICKVIEW                    40012
#define IDM_PICKBUFFER                  40013
#define IDM_OBJ_DIALOG                  40014
#define ID_FILE_SAVE_HEIGHT             40015
#define ID_FILE_SAVE_MAP                40016
#define IDM_COMM_CONNECT                40017
#define ID_TEST_ADDPLAYER               40018
#define ID_TEST_DELPLAYER               40019
#define ID_TEST_ATTACK                  40020
#define IDM_VIEW_SHADOW                 40021
#define IDM_MAP_OPEN                    40022
#define IDM_SHOWSTAT                    40023
#define IDM_FASTMOVE                    40024
#define ID_COMM_WINDOWSDEBUG            40026
#define ID_COMM_WINDEBUG                40028

// Next default values for new objects
//
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        142
#define _APS_NEXT_COMMAND_VALUE         40029
#define _APS_NEXT_CONTROL_VALUE         1019
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
